##Crear autor

POST http://localhost:3000/author/
Content-Type: application/json

{
  
}


###Obtener autor

GET http://localhost:3000/author/3
Content-Type: application/json

{
  
}

###Obtener autor

GET http://localhost:3000/bookAuthor/3
Content-Type: application/json

{
  
}


###Modificar autor

PUT http://localhost:3000/autor
Content-Type: application/json

{
  
}

###Modificar autor

DELETE http://localhost:3000/autor
Content-Type: application/json

{
  
}
