##Crear autor - Funcionando

POST http://localhost:3000/author/
Content-Type: application/json

{
  "name":"Test"
}

###
##Editar autor - Funcionando

PUT http://localhost:3000/author/16
Content-Type: application/json

{
  "name":"Test"
}


###Obtener autor - Funcionando

GET http://localhost:3000/author/3
Content-Type: application/json

{
  
}

###Obtener todos los autores - Funcionando

POST http://localhost:3000/author/all
Content-Type: application/json

{
 
}

###Obtener todos los autores activos - Funcionando

POST http://localhost:3000/author/allActive
Content-Type: application/json

{
 
}

###Obtener libro-autor - Funcionando

GET http://localhost:3000/bookAuthor/3
Content-Type: application/json

{
  
}


###Modificar autor

PUT http://localhost:3000/autor
Content-Type: application/json

{
  
}

###Modificar autor

DELETE http://localhost:3000/autor
Content-Type: application/json

{
  
}
