##Crear libro

POST http://localhost:3000/libro
Content-Type: application/json

{
  
}


### Obtener libro - Funcionando !!

GET http://localhost:3000/book/3
Content-Type: application/json

{
 
}

###Modificar libro

PUT http://localhost:3000/book
Content-Type: application/json

{
  
}

###Modificar libro

DELETE http://localhost:3000/libro
Content-Type: application/json

{
  
}

####
###Modificar libro

POST http://localhost:3000/book/byPublisher
Content-Type: application/json

{
  "publisher":"Alianza"
}


