###Obtener libro - Funcionando 

GET http://localhost:3000/genre/11
Content-Type: application/json

{
 
}

###Obtener libro genre - Funcionando

GET http://localhost:3000/bookGenre/11
Content-Type: application/json

{
 
}

###Obtener todos los genres - Funcionando

POST http://localhost:3000/genre/all
Content-Type: application/json

{
 
}

###Obtener todos los genres - Funcionando

POST http://localhost:3000/genre/allActive
Content-Type: application/json

{
 
}

####
##Crear genre - Funcionando

POST http://localhost:3000/genre/
Content-Type: application/json

{
  "name":"Misterio"
}

####
##Modificar genre - Funcionando

PUT http://localhost:3000/genre/1
Content-Type: application/json

{
  "name":"Misterio Modificado"
}

###
###Delete genre - Funcionando

DELETE http://localhost:3000/genre/1
Content-Type: application/json

{
  
}

###Activate genre - Funcionando

PUT http://localhost:3000/genre/activate/1
Content-Type: application/json

{
  
}
