##Crear usuario
POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "claudia",
  "password": "mysecretpassword",
  "firstName": "John",
  "lastName": "Doe",
  "phone": 123456789,
  "region": "Region",
  "address": "Address",
  "zipCode": 123
}

###Obtener usuario sin token

GET http://localhost:3000/user/12777d98-1951-4c4f-814f-7a8e0c90462c
Content-Type: application/json

{
  
}

###Obtener usuario sin token

GET http://localhost:3000/user/11
Content-Type: application/json

{
  
}

###Obtener usuario con token invalido

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNsYXVkaWEiLCJpYXQiOjE3MTAyMDY3OTksImV4cCI6MTcxMDIwNzM5OX0.CrYqB1XIvsJ2GscKkx4h92-Je49OByV1i2SwEUu-_mI
GET http://localhost:3000/user/userId=12777d98-1951-4c4f-814f-7a8e0c90462c
Content-Type: application/json
Authorization: Bearer {{token}}

{
  
}

###Modificar usuario

PUT http://localhost:3000/usuario
Content-Type: application/json

{
  
}

###Modificar usuario

DELETE http://localhost:3000/usuario
Content-Type: application/json

{
  
}
