##Crear usuario
POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "claudia",
  "password": "mysecretpassword",
  "firstName": "John",
  "lastName": "Doe",
  "phone": 123456789,
  "region": "Region",
  "address": "Address",
  "zipCode": 123
}

###Obtener usuario sin token

GET http://localhost:3000/user?id=12777d98-1951-4c4f-814f-7a8e0c90462c
Content-Type: application/json

{
  
}

###Obtener usuario con token invalido

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJwZXBpdG8zQGdtYWlsLmNvbSIsImlhdCI6MTcwODQ4NTkzOCwiZXhwIjoxNzA4NDg5NTM4fQ.rvALpuHO365SjzMidBniP8k761UWMliH1gNNfKkx_lw
GET http://localhost:3000/user?id=12777d98-1951-4c4f-814f-7a8e0c90462c
Content-Type: application/json
Authorization: Bearer @{{token}}

{
  
}

###Modificar usuario

PUT http://localhost:3000/usuario
Content-Type: application/json

{
  
}

###Modificar usuario

DELETE http://localhost:3000/usuario
Content-Type: application/json

{
  
}
