##Crear usuario
POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "claudia",
  "password": "mysecretpassword",
  "firstName": "John",
  "lastName": "Doe",
  "phone": 123456789,
  "region": "Region",
  "address": "Address",
  "zipCode": 123
}

###Obtener usuario

GET http://localhost:3000/usuario
Content-Type: application/json

{
  "id": "12777d98-1951-4c4f-814f-7a8e0c90462c"
}

###Modificar usuario

PUT http://localhost:3000/usuario
Content-Type: application/json

{
  
}

###Modificar usuario

DELETE http://localhost:3000/usuario
Content-Type: application/json

{
  
}
